# Generated by Django 4.1.1 on 2023-01-29 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bss', '0002_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uname', models.CharField(max_length=30)),
                ('umobile', models.CharField(max_length=10)),
                ('uaddress', models.CharField(max_length=100)),
                ('umessage', models.CharField(max_length=100)),
                ('ngoname', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bss.zip')),
                ('uemail', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bss.uregister')),
            ],
        ),
    ]
