# Generated by Django 4.1.1 on 2023-01-29 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bss', '0003_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='ngoname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='upload',
            name='uemail',
            field=models.EmailField(max_length=255, unique=True),
        ),
    ]
