# Generated by Django 4.1.1 on 2023-01-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bss', '0004_alter_upload_ngoname_alter_upload_uemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='ustatus',
            field=models.CharField(default='Pending', max_length=30),
        ),
    ]
