# Generated by Django 4.1.1 on 2023-01-29 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bss', '0005_upload_ustatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='uemail',
            field=models.EmailField(max_length=255),
        ),
    ]
