# Generated by Django 4.1.1 on 2023-01-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bss', '0006_alter_upload_uemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='zip',
            name='password',
            field=models.CharField(default=1, max_length=64),
            preserve_default=False,
        ),
    ]
