# Generated by Django 4.1.1 on 2023-02-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bss', '0007_zip_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upload',
            name='ngoname',
        ),
        migrations.AddField(
            model_name='upload',
            name='ngoemail',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
