# Generated by Django 4.1.1 on 2023-02-02 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bss', '0008_remove_upload_ngoname_upload_ngoemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='ngoname',
            field=models.CharField(default='malabar', max_length=30),
            preserve_default=False,
        ),
    ]
